image:
  file: .gitpod.Dockerfile

tasks:
  - before: |
      make setup
    command: |
      make dev-node/start
      make build
  - init: |
      make clean
      make build
  - init: |
      yarn --cwd interface && yarn start 

ports:
  - port: 1317
    visibility: public
  - port: 3000
    visibility: public
  - port: 5000
    visibility: public
  - port: 9091
    visibility: public
  - port: 26657
    visibility: public

vscode:
  extensions:
    - matklad.rust-analyzer
    - esbenp.prettier-vscode
    - bungcip.better-toml
