image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      make init
    command: |
      make dev-node/start
  - init: |
      make clean
      make build
  - init: |
      yarn --cwd functional-tests
      yarn --cwd interface && yarn start

ports:
  - port: 9091
    visibility: public

vscode:
  extensions:
    - matklad.rust-analyzer
    - esbenp.prettier-vscode
    - bungcip.better-toml
