image:
  file: .gitpod.Dockerfile

tasks:
  - before:
      make setup && \
      make build

  - init:
      make dev-node/start && \
      sleep 10 && \
      yarn test-counter
  
  - init: |
      export EDITOR="command gp open -w" VISUAL="command gp open -w"
      cp -f /workspace/ohmyzsh/templates/zshrc.zsh-template ~/.zshrc
      ln -sf /workspace/ohmyzsh ~/.oh-my-zsh
    command: exec zsh

  - command: |
      yarn --cwd interface start 

ports:
  - port: 1317
    visibility: public
  - port: 3000
    visibility: public
  - port: 5000
    visibility: public
  - port: 9091
    visibility: public
  - port: 26657
    visibility: public

vscode:
  extensions:
    - matklad.rust-analyzer
    - esbenp.prettier-vscode
    - bungcip.better-toml
