tasks:
  - init: |
      make init
    command: |
      make dev-node/start
  - init: |
      yarn --cwd interface && yarn start

vscode:
  extensions:
    - matklad.rust-analyzer
    - esbenp.prettier-vscode
    - bungcip.better-toml
